softeerbootcamp-3rd/Team9-HexaCore

README.md

- 서비스 한 줄 소개 문구 괜찮은지 확인해주세요.
- 문서 정리에 저희팀 노션 링크를 연결해뒀는데 공개하고 싶지 않을 경우 말해주세요.
- 우리의 도전들 항목에 각자 기록하고 싶은 글들을 위키나 노션에 정리한 후 첨부해주시면 됩니다. (개인적으로 위키나 노션 중 하나로 통일하는게 좋을 것 같긴 한데 의견 주십숑!)
close #9

[FE/BE] #9: 리드미 프로젝트 소개, 그라운드 룰, 개발 컨벤션, 기획/디자인 문서 정리

---

client/src/App.tsx

close #18 
페이지 제작 시 가장 상위 태그에 `h-full` 클래스를 넣으시면 전체 페이지 크기로 만드실 수 있습니다.
회원 가입, 로그인 페이지의 경우 아래와 같이 만들 수 있겠네요!
```jsx
function Login() {
return (
<div className="h-full flex justify-center items-center">
// form
</div>
);
}
```
만약 전체화면보다 페이지가 커 스크롤이 된다면 `h-full` 클래스를 굳이 추가하지 않아도 되겠네요!

[FE] #18: 모든 페이지의 main 최소 전체 화면으로 수정

---

server/src/main/java/com/hexacore/tayo/car/CarController.java
server/src/main/java/com/hexacore/tayo/car/CarRepository.java
server/src/main/java/com/hexacore/tayo/car/CarService.java
server/src/main/java/com/hexacore/tayo/car/model/CarEntity.java
server/src/main/java/com/hexacore/tayo/car/model/DateListDto.java
server/src/main/java/com/hexacore/tayo/common/ResponseCode.java

- 예약 가능 날짜를 수정하는 api를 구현하였습니다.
- 아직 세션을 어떤 방식으로 관리할지 정해진 것이 없어 추후 세션에 따라 권한이 있는지 없는지 판단하는 로직을 추가하여야 합니다.
close #28

[BE] 차량 예약 가능 날짜 수정 api 구현

---

client/src/components/Tag.tsx
client/src/pages/hosts/CarData.json
client/src/pages/hosts/HostManage.tsx
client/src/pages/hosts/hostsRoutes.tsx

close #15 
- 분기
- 등록된 차량이 없을때 -> 차량 등록 페이지로 이동하기
- 수정/ 삭제시 -> 페이지 reload
- 차량 정보 카드 개발
- 더미 데이터를 사용해서 html과 css를 작성 하였습니다.
- 스크린샷 보고 피드백 주시면 수정하겠습니다.
- 렌더링 영역 분리
- 공통 컴포넌트를 삽입 할 영역을 분리하였습니다.

[FE] #15 : 호스트 페이지 개발

---

client/src/components/TitledBlock.tsx
client/src/pages/hosts/HostRegister.tsx
client/src/pages/hosts/ImageUploadButton.tsx
client/src/pages/hosts/hostsRoutes.tsx
client/src/pages/profile/Profile.tsx
client/src/pages/profile/profileRoutes.tsx

- 잘못 입력된 타입 들 수정했습니다.
- `String` -> `string`
- `Number` -> `number`
- 잘못 사용된 훅 수정했습니다.
- 훅은 콜백으로 사용하면 안되고 컴포넌트 함수 블록 안에서 사용되어야 합니다.
- 차량 등록 화면 레이아웃을 조금 수정했습니다.
- 수정 과정에서 ref로 관리 하던 이미지와 오류 메세지를 state로 관리 하도록 변경했습니다.

[FE] #46: 타입, 경로, react hook 잘못 사용한 부분 등 오류 수정, 차량 등록 화면 페이지 레이아웃 수정

---

client/src/pages/profile/Profile.tsx

close #91 
- 유저 정보 카드 영역의 높이를 h-auto로 적용
- 카드 안의 요소들의 높이는 고정값으로 적용
Before
After

[FE] #91: 마이페이지 버그 수정

---

.github/workflows/fe-vite.yml
client/package.json

- 배포 파이프라인
- github pages를 사용한 배포 환경 사용
- 동작 방식
1. main에 merge
2. github action 실행
3. npm run build 실행 -> /dist에 build된 파일들 저장
4. build 된 파일들을 gh-pages branch에 push
5. 배포
- 코드 컨벤션
- 동작방식 3번에 npm run build를 실행할때, tsc && vite build가 실행되는데 이때 코드 컨벤션을 지키지 않은 코드가 있으면 에러 발생
- npm run dev실행시에도 에러가 발생하게 변경하여 배포 실패를 차단
- package.json에 homepages 설정
- domain구입후 git hub pages에 연결
- image 파일 불러오는지 test

[FE] #111프론트엔드 배포 파이프라인 구축

---

server/src/main/java/com/hexacore/tayo/auth/AuthService.java
server/src/main/java/com/hexacore/tayo/car/model/Car.java
server/src/main/java/com/hexacore/tayo/user/UserController.java
server/src/main/java/com/hexacore/tayo/user/UserService.java
server/src/main/java/com/hexacore/tayo/user/model/User.java

- User, Car OneToOne 양방향 매핑 -> Car ManyToOne 단방향 매핑으로 수정
- User 클래스에서 car 필드 삭제, Car 클래스에서 OneToOne -> ManyToOne 어노테이션으로 변경
- 코드 수정에 따라 에러가 발생하는 부분을 주석 처리하고 "TODO: #135 이슈" 라고 적어놨습니다. 에러가 나는 상태 그대로 푸시하는 것보다 이렇게 하는 편이 코드 병합할 때 더 좋을 것 같아 이렇게 했는데, 확인 부탁드립니다!
- AuthService
- UserService
- UserController
위 클래스에서 주석처리 해놓은 부분 담당자분들 확인하고 수정 부탁드립니다! 각각의 이슈를 따로 생성해서 수정할 지, #135 이슈 그대로 사용할 지 논의가 필요합니다.

[BE] #135: User 엔티티 클래스에서 Car 와 One-To-One 매핑 처리 문제

---

client/src/pages/home/Home.tsx

close(#140)
- before: 검색 API에서 500 에러가 발생하면 데이터가 오지 않아 undefined 객체에 접근하게 되어 에러가 발생
- after: 응답 객체가 undefiend 경우 예외처리 추가
자세한 에러 상황은 #140 참고 부탁드립니다.

[FE] #140: 검색 화면에서 검색 결과를 받아오지 못하는 경우 에러 발생

---

server/src/main/java/com/hexacore/tayo/car/CarService.java
server/src/main/java/com/hexacore/tayo/category/CategoryRepository.java
server/src/main/java/com/hexacore/tayo/category/CategoryService.java
server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java

close(#146)
- 이슈 #146 참고 부탁드립니다!

[BE] #146: 세부 모델명 조회 API 쿼리 성능 개선 (N+1 문제 해결)

---

server/src/main/java/com/hexacore/tayo/car/CarRepository.java
server/src/main/java/com/hexacore/tayo/car/CarService.java
server/src/main/java/com/hexacore/tayo/user/UserController.java
server/src/main/java/com/hexacore/tayo/user/UserService.java

close #155 
- carRepository 변경
- findByOwner_IdAndIsDeletedFalse함수는 하나의 객체를 반환하기 때문에 List -> Optional로 변경하였습니다.
- userIsHavingCar 함수도 Optional로 변경하였습니다
- 피드백 부탁드립니다 @Yoon-Suji 
- 유저의 차량을 조회하는 API를 수정된 DB에 맞게 변경

[BE] #155 내차 가져오기 API 리팩토링 

---

client/src/components/ListComponent.tsx
client/src/fetches/reservations/Reservation.type.ts
client/src/pages/hosts/HostManage.tsx
client/src/pages/hosts/hostsRoutes.tsx
client/src/pages/profile/Profile.tsx
client/src/pages/profile/profileRoutes.tsx

[FE] #170 호스트 페이지 & 게스트 페이지 버그 수정 

---

server/src/main/java/com/hexacore/tayo/auth/jwt/dto/GetTokenResponseDto.java
server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsResultDto.java
server/src/main/java/com/hexacore/tayo/category/dto/GetCategoriesResponseDto.java
server/src/main/java/com/hexacore/tayo/common/response/Response.java
server/src/main/java/com/hexacore/tayo/interceptor/LoggingInterceptor.java
server/src/main/java/com/hexacore/tayo/reservation/dto/GetCarSimpleResponseDto.java
server/src/main/java/com/hexacore/tayo/reservation/dto/GetGuestReservationListResponseDto.java
server/src/main/java/com/hexacore/tayo/reservation/dto/GetGuestReservationResponseDto.java
server/src/main/java/com/hexacore/tayo/reservation/dto/GetHostReservationListResponseDto.java
server/src/main/java/com/hexacore/tayo/reservation/dto/GetHostReservationResponseDto.java
server/src/main/java/com/hexacore/tayo/user/dto/GetUserInfoResponseDto.java
server/src/main/java/com/hexacore/tayo/user/dto/GetUserSimpleResponseDto.java
server/src/main/java/com/hexacore/tayo/user/dto/LoginResponseDto.java

- 현재 로그에 찍히는 정보 중 controller의 실행 결과에 대한 로깅이 데이터가 보이지 않고 객체의 레퍼런스 값이 보이고 있어 데이터 정보가 보이도록 수정하였습니다.
- 앞으로 response와 관련된 dto들을 만들 때 toString()을 오버라이딩 해 주면 좋을 것 같아요!
- close #167

[BE] #167: 응답 dto에 toString() 메소드 추가

---

client/src/fetches/cars/cars.type.ts
client/src/fetches/cars/fetchCars.ts
client/src/fetches/categories/fetchCategories.ts
client/src/fetches/common/response.type.ts
client/src/pages/home/CarCard.tsx
client/src/pages/home/Home.tsx
client/src/pages/home/homeRoutes.tsx

close(#188)
* #185 PR 변경사항을 반영하여 검색 API 호출하는 로직 수정 진행

[FE] #188: 검색 API 수정에 따른 프론트 수정

---

client/src/fetches/users/fetchUser.ts
client/src/pages/cars/Payment.tsx
server/src/main/java/com/hexacore/tayo/car/CarService.java
server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java

- 백엔드 머지 과정에서 잘못 병합된 부분 해결
- navigate 하드코딩 수정
- 프론트에서 결제 요청 url 대소문자 수정

[FE, BE] 결제 모듈 에러 수정

---

server/src/main/java/com/hexacore/tayo/car/CarService.java
server/src/main/java/com/hexacore/tayo/car/model/CarType.java
server/src/main/java/com/hexacore/tayo/car/model/FuelType.java
server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java

- CarType과 FuelType에서 NOT_FOUND를 삭제하고 존재하지 않은 타입이 들어왔을 경우 예외를 던지도록 수정하였습니다.
- close #203

[BE] #203: FuelType과 CarType에서 NOT_FOUND 삭제

---

client/src/fetches/reservations/fetchHostReservations.ts
client/src/pages/cars/CarDetail.tsx
client/src/pages/hosts/HostManage.tsx
client/src/utils/converters.ts

- Date 객체를 서버로 전송할 때 axios의 JSON 직렬화 과정에서 Date 타입을 UTC 타임존 값으로 날짜를 변환해줍니다. 따라서 날짜 정보를 서버로 보낼 때는 스트링 타입으로 변환한 후 보내줘야 합니다.

[FE] !HOTFIX: 날짜 서버로 전송 시 타임존 이슈

---

server/src/main/java/com/hexacore/tayo/car/CarService.java
server/src/main/java/com/hexacore/tayo/car/dto/UpdateCarRequestDto.java

close #90 
- 차량 업데이트 시에 이미지를 변경하지 않으면 이미지 index리스트와 이미지 file 리스트에 null 값이 요청됨.
- null값일때 에러가 발생하지 않도록 null check를 추가

[BE] #90 : 차량 조회 수정 API 리팩토링 

---

server/.gitignore

* server/.gitignore 파일에 /log/ 경로를 추가했습니다.

[BE] HOTFIX: .gitignore에 log 폴더 추가

---

server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java

close #151 
- 투 포인터 알고리즘을 적용하여 시간 복잡도를 O(N^2) -> O(N+M)으로 변경

[BE] #151 : 차량 조회 DTO 알고리즘 개선 

---

.github/workflows/fe-vite.yml

[x] package.json의 위치로 이동시키는 로직 추가

[FE] #111 : 프론트엔드 배포 파이프라인 구축

---

server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java

[BE] hotfix: 예약 거절 알림 전송 상대 머지 이슈 해결

---

server/src/main/java/com/hexacore/tayo/car/carRepository/CustomCarRepositoryImpl.java
server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsDto.java

[BE] refactor: 검색 API 여러 종류의 차 종류 선택 가능 하도록 수정, 예약 된 구간 검색되는 버그 수정

---

server/src/main/java/com/hexacore/tayo/car/carRepository/CustomCarRepositoryImpl.java
server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsDto.java
server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java

* 호스트가 예약 거절 시 호스트에게 알람이 가는 오류 해결
* 검색 API에서 CarType을 여러 개 선택하지 못하는 오류 해결

[BE] 백엔드 배포 진행

---

README.md

* 리드미에 주요 기능, 이슈 및 논의 내용, PR, 인프라 아키텍쳐, ERD, 기술 스택 등의 내용을 추가했습니다.

[README] 리드미 업데이트

---

README.md

- erd 테이블 사진이 잘못 올라가있어 수정하였습니다.

[README] erd 테이블 사진 수정

---

README.md

- 리드미에서 팀 노션을 제외하고 API 명세서 페이지를 추가하였습니다.

[README] 리드미 API 명세서 업데이트
