client/src/App.tsx
페이지가 최대 회면을 넘어갔을 때 배경은 늘어나지 않는 버그 수정
`min-height: 100vh;` 의 경우 hight이 설정되지 않은 것으로 간주되어 내부에서 height:100% 가 적용되지 않아요...
따라서 flex와 grow를 추가로 사용해 페이지에서 `h-full`이 적용되고 페이지가 `height: screen`을 넘어가도 `App`이 늘어나도록 수정했어요!
=> [FE] #18: 페이지가 최대 회면을 넘어갔을 때 배경은 늘어나지 않는 버그 수정

.github/workflows/be-gradle.yml, server/Dockerfile
close #23 
- `DockerFile`: 도커 이미지 빌드를 위한 설정 파일입니다. JDK 17 환경에서 .jar 실행파일을 실행하는 명령어를 담고 있습니다.
- `be-gradle.yml`: 깃허브 액션 워크플로우 정의 파일입니다. 
- `deploy` 브랜치에 `push` 이벤트가 발생하면 자동으로 트리거되도록 설정
- 깃허브 액션 빌드 서버에서 스프링부트 웹서버를 빌드하고 Docker Hub에 push
- EC2에 ssh 를 이용해서 접속하여 Docker Hub의 이미지를 pull 받아 실행
=> [BE] #23: 백엔드 서버 배포 파이프라인 구축

server/src/main/resources/application.properties
- 기존 고화질 사진을 업로드 할 때 아래와 같은 오류가 떠서 알아보니 스프링 애플리케이션에서는 기본적으로 파일 업로드 크기를 제한하고 있어서 업로드 가능한 최대 크기를 20MB로 수정하였습니다. 20MB로 잡은 이유는 핸드폰으로 사진을 찍었을 때의 사진 하나의 사이즈가 3MB 정도여서 5장의 사진을 업로드 할 경우 넉넉하게 20MB가 필요할 것이라 판단하였습니다.
```json
{
"success": false,
"code": 500,
"message": "Maximum upload size exceeded"
}
```
close #45
=> [BE] #45: 파일 업로드 크기 20BM로 제한

server/src/main/java/com/hexacore/tayo/common/ResponseDto.java, server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java, server/src/main/java/com/hexacore/tayo/common/errors/ErrorExceptionHandler.java
- getBindingResult 메서드를 통해 데이터 바인딩 및 유효성 검사를 수행한 결과를 담고 있는 객체를 받아와 해당 결과에서 에러메시지를 추출하여 ResponseDto의 메시지 값으로 반환되도록 구현하였습니다.
예를 들어 유저 로그인 시 이메일 형식이 맞는지 확인하는 과정을 `@Valid` 를 통해 검증한다고 가정하면, (컨트롤러에서 검증할 dto 앞에 붙여주면 됩니다.)
```java
public class LoginDto {
@NotBlank(message = "이메일은 필수 입력 값입니다.")
@Email(message = "이메일 형식에 맞지 않습니다.")
private String email;
// 다른 필드값
}
```
다음과 같이 로그인 dto에서 지정한 유효성 검증 메시지에 대해 올바르지 않은 입력값을 보냈을 때 사전에 지정한 ResponseDto의 message가 유효성 검증 메시지 값으로 설정되어 반환됩니다.
close #64
=> [BE] #64: MethodArgumentNotValidException 예외처리 추가

server/build.gradle, server/src/main/java/com/hexacore/tayo/car/CarController.java, server/src/main/java/com/hexacore/tayo/car/CarRepository.java, server/src/main/java/com/hexacore/tayo/car/CarService.java, server/src/main/java/com/hexacore/tayo/car/model/ModelEntity.java, server/src/main/java/com/hexacore/tayo/car/model/PostCarDto.java, server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java, server/src/main/java/com/hexacore/tayo/user/UserRepository.java, server/src/test/java/com/hexacore/tayo/car/CarControllerTest.java, server/src/test/java/com/hexacore/tayo/car/CarRepositoryTest.java, server/src/test/java/com/hexacore/tayo/car/CarServiceCreateCarTest.java, server/src/test/java/com/hexacore/tayo/car/CarServiceDeleteCarTest.java, server/src/test/java/com/hexacore/tayo/car/CarServiceGetCategoriesTest.java, server/src/test/java/com/hexacore/tayo/car/ModelRepositoryTest.java
close #61 
- Repository: JPA에서 기본으로 제공해주는 메소드 외에 Repository에 선언해서 사용한 메서드들에 대해 단위 테스트 코드 작성
- DataJpaTest 어노테이션 사용: 경량화된 테스트 환경 구축, 트랜잭션 롤백 기능 제공
- AutoConfigureTestDatabase 어노테이션 사용: 임베디드 데이터베이스가 아닌 MySQL 데이터베이스를 사용하기 위함
- CarService: 메서드 별로 클래스를 나누어 단위 테스트 코드 작성
- Mockito를 이용해서 Repository, AmazonS3Client 객체를 모킹해서 서비스 자체의 로직에만 집중해서 코드 작성
- CarController: MockMvc와 Mockito를 이용해서 컨트롤러 자체의 로직에만 집중해서 테스트 코드 작성
- ModelEntity의 subCategory 컬럼에 unique 조건을 추가했습니다 -> subCategory의 값은 unique해야 하고 데이터의 수정보다 조회가 자주 일어나는 컬럼 + MySQL에서 unique 조건에 자동으로 인덱싱을 추가해주기 때문에 조회 시 성능 향상
* Valid 어노테이션을 사용해서 PostCarDto에서 필수로 넘어와야 하는 값들에 NotNull 어노테이션을 추가했습니다.
* CarService 에서 예외 처리 케이스를 추가했습니다.
- isIndexSizeEqualsToImageSize: imageIndexes 리스트와 imageFiles 리스트 사이즈가 같은지 비교
- uploadImage 에서 파일의 contentType이 이미지가 아닌 경우 …
=> [BE] #61: 차량 등록, 삭제, 세부 모델 조회 API - 테스트 코드 작성

server/src/main/java/com/hexacore/tayo/common/response/Response.java
- 기존 status만 받아와 response를 만드는 함수에서 data의 값을 null로 설정하여 반환하던 부분이 메소드 명을 전부 통일하며 PageInfo를 만드는 메소드로 넘어가는 에러가 있었습니다. 이에 해당 부분을 직접 ResponseEntity를 만들도록 코드를 수정하였습니다.
=> [BE] #72: Status에 대한 응답 반환 형태 수정

client/src/pages/auth/InputBox.tsx, client/src/pages/auth/Login.tsx, client/src/pages/auth/SignUp.tsx
* close #100
* 회원가입 성공 시에 메인 페이지로 이동
* 닉네임 제거
* 회원가입 성공 시에 로그인 페이지로 이동
영문, 숫자, 기호 포함 6자 이상 입력해야 했는데,
개발과정에서 유저 생성해보고 테스트해보는 과정에서 어려울 것 같아 비밀번호는 패턴 체크 일단 주석처리 해놓았습니다.
회원가입 성공하면 로그인 페이지로 이동하게 했습니다.
* 형식에 맞지 않거나 입력하지 않은 경우 요청 안보냄
* 같은 이메일로 가입한 유저가 있는 경우 중복된 유저입니다.
https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/80809782/de55be8a-306e-46ed-88ef-09837638a209
* 아이디나 비밀번호 입력하지 않은 경우 요청 보내지 않음 - 입력해주세요.
* 가입하지 않은 유저 or 비밀번호 틀린 경우 or 서버 에러 - 올바른 이메일, 비밀번호를 입력해주세요.
https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/80809782/d46f41ec-6437-46c5-96e3-93d22339c0b0
=> [FE] #100: 로그인, 회원가입 api 연동

client/src/fetches/auth/auth.type.ts, client/src/fetches/common/axios.ts, client/src/pages/auth/Login.tsx, server/src/main/java/com/hexacore/tayo/auth/AuthController.java, server/src/main/java/com/hexacore/tayo/auth/AuthService.java, server/src/main/java/com/hexacore/tayo/auth/jwt/dto/GetTokenResponseDto.java, server/src/main/java/com/hexacore/tayo/config/InterceptorConfig.java, server/src/main/java/com/hexacore/tayo/interceptor/AuthenticationInterceptor.java, server/src/main/java/com/hexacore/tayo/user/dto/LoginResponseDto.java, server/src/main/java/com/hexacore/tayo/util/RequestParser.java
- close #110 
로그인 요청시 엑세스 토큰과 리프레시 바디로 받아 Document.setcookie를 통해 쿠키에 jwt 토큰을 설정해주도록 수정합니다.
하지만 쿠키 설정 이슈로 인해
Authorization 헤더에 넘기는 것으로 수정했습니다.
써드 파티 쿠키는 브라우저에 설정이 안되는 문제와, 해당 쿠키가 서버에 전송되지 않는 문제가 있는데,
이는 나중에 자세히 알아보도록 하겠습니다!
추후에 Authorization 헤더, 쿠키의 차이에 대해 자세히 알아볼 예정입미다!
=> [FE, BE] #110: jwt 토큰을 로컬 스토리지에 저장하도록 수정

server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
```java
for (CarDateRange carDateRange : carDateRanges) {
LocalDate startDate = carDateRange.getStartDate();
LocalDate endDate = carDateRange.getEndDate();
// 포함되는 예약 가능 구간을 찾을 때 까지는 continue;
if (!localDateInclusiveAfter(endDate, returnDateTime.toLocalDate()) ||
!localDateInclusiveBefore(startDate, rentDateTime.toLocalDate())) {
continue;
}
for (Reservation reservation : carDateRange.getReservations()) {
if (reservation.getStatus() == ReservationStatus.READY ||
reservation.getStatus() == ReservationStatus.USING) {
if (!reservation.getReturnDateTime().isBefore(rentDateTime)
|| !reservation.getRentDateTime().isAfter(returnDateTime)) {
throw new GeneralException(ErrorCode.RESERVATION_ALREADY_READY_OR_USING);
}
}
}
return carDateRange;
}
```
- 기존 로직에서는 반납일이 항상 예약이 되어있는 시작 날짜보다 앞인 경우에만 예약이 …
=> [BE] #125: 예약 정보 업데이트 시 validation 버그 수정

server/src/main/java/com/hexacore/tayo/interceptor/AuthenticationInterceptor.java
- close #118
- 요청을 보낼 때, 해당 요청이 안전한 요청인지 확인하기 위해 OPTIONS 메소드로 미리 서버에 요청을 보내보는데, 이에 대해서도 사용자 인증을 거치는 문제가 발생하여 OPTIONS 요청에 대해서는 인터셉터를 거치지 않도록 합니다.
- 차량을 검색하는 api는 인터셉트를 통과하도록 합니다.
=> [BE] #118: 인터셉터 허용 메소드, 경로 추가

server/src/main/java/com/hexacore/tayo/car/CarService.java, server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
close(#138)
- 차량을 삭제하기 전 차량에 연결된 예약 중 상태가 READY 혹은 USING인 것이 있으면 삭제하지 못하고 에러를 발생하게 수정했습니다.
- 프론트 호스트 관리 페이지에서 해당 에러를 받으면 사용자에게 차량을 삭제하려면 예약을 모두 삭제한 뒤 재시도하라고 알려줘야할 것 같습니다. @jomulagy 지훈님 호스트 관리 페이지 담당이신 것 같아서 태그합니다 :)
- 차량 수정 부분에서 현재 이미지 소프트 딜리트 방식으로 구현하고 있어서 CarImage 엔티티 클래스에서 isDeleted 필드를 아직 삭제하지 않았습니다. 해당 부분 수정하시고 삭제해주시면 감사하겠습니다. @jomulagy
=> [BE] #138: DB 변경사항 반영하여 차량 삭제 API 수정

server/src/main/java/com/hexacore/tayo/car/CarService.java, server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
close #157 
- 기존: updateDateRanges에서 모든 예약 가능 구간 이후의 예약이 있는지를 검증하지 못함
- 투 포인터를 사용한 검증 방식에서 예약 가능한 구간이 남지 않았는데 예약이 남은 경우를 검증하지 못한 부분 수정
=> [BE] #157: 예약 가능 날짜 업데이트 API 버그 수정

client/src/pages/cars/CarDetail.tsx
- 대여 날짜 및 시간과 반납 날짜 및 시간이 정확하게 일치할 경우 예약을 하지 못 하도록 수정하였습니다.
- 예외 상황에 대해 현재는 alert로 경고 창을 띄우고 있는데 전체적으로 어떻게 예외 상황을 핸들링하면 좋을지 논의가 필요해 보입니다.
=> [FE] #177: 대여시각과 반납시각이 일치할 경우 예약하지 못 하도록 수정

server/src/main/java/com/hexacore/tayo/car/CarController.java, server/src/main/java/com/hexacore/tayo/car/CarService.java
close(#176)
현재 차량 삭제 API 에서 차량을 soft delete 처리하고 연결된 이미지를 hard delete 처리하고 있지만, 차량에 매핑된 reservation과 car_date_range에 대한 처리는 하지 않고 있습니다. reservation은 차량이 삭제되어도 게스트가 예약 내역에서 확인할 수 있어야 하기에 따로 처리를 하지 않지만, car_date_range의 경우에는 추후 유저가 같은 번호의 차량을 재등록했을때 이전에 설정했던 car_date_range가 불러와지는 것은 논리적으로 맞지 않으므로 차량을 삭제할 때 연결된 car_date_range도 모두 하드 딜리트 하도록 수정했습니다.
=> [BE] #176: 차량 삭제 시 연결된 car_date_range 하드 딜리트

server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsResultDto.java
close(#193)
- dev 브랜치의 SearchCarsResultDto 에서 toString() 메서드가 중복으로 선언되어 있어서 에러가 발생합니다. 수현님이 작성한 toString 메서드만 남기고 삭제했습니다.
=> [BE] #193:  toString() 메서드 중복 에러

server/src/main/java/com/hexacore/tayo/car/CarService.java, server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java, server/src/main/java/com/hexacore/tayo/user/UserService.java
- 기존 코드에서는 호스트가 차량 상세 정보를 조회할 때와 게스트가 차량 상세 정보를 조회할 때 모두 예약 가능한 구간이 reservation 테이블에 예약이 걸려있는 날짜 구간이 제외되고 있었습니다. 하지만, 호스트가 본인의 차량 관리를 할 때에는 호스트가 열어둔 모든 예약 가능 구간이 필요하기 때문에 해당 로직을 분리하였습니다.
- close #195
=> [BE] #195: 호스트 차량 정보 조회 api 수정

client/src/pages/hosts/HostRegister.tsx, server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
close #183 
- BE 코드를 수정한 부분은 GetCarResponseDto에서 OrderIdx가 정렬된 상태로 전달하도록 수정한 부분입니다.
- 사진을 추가/변경하면 대여료의 값이 변경되는 점을 수정
- 다음과 같은 코드로 데이터허브 API의 연료 형식을 재분류하였습니다.
```typescript
const convertFuelType = (fuel: string) => {
if (fuel === '가솔린') return '휘발유';
if (fuel === '디젤') return '경유';
if (fuel === 'LPG') return 'LPG';
if (fuel === '전기') return '전기';
if (fuel === '수소전기') return '수소';
return '';
};
```
=> [FE] #183: 차량 등록/수정 페이지 관련 수정

server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsDto.java
- #205 
- #204  
위 PR의 변경 사항으로 인해 검색 조건에 `CarType`을 입력하지 않을 경우 예외가 응답됩니다.
`CarType`이 입력되지 않았을 경우 검색 조건에서 제외하고 검색하는 것이 정상 동작입니다.
=> [BE] #205: SearchCarsDto에서 type이 null일 경우 CarType enum을 사용하지 않음

client/src/components/notification/NotificationBox.tsx, client/src/pages/auth/Login.tsx
- close #234 
현재 SSE를 위해 클라리언트에서 처음에 구독 요청을 보내고 있습니다.
하지만 이벤트를 수신할 eventSource가 기본적으로 45초동안 아무 이벤트가 수신되지 않으면 다시 연결을 요청합니다.
45초는 너무 짧다고 판단되며 현재 서버에서는 이벤트를 보내는 SseEmitter 객체를 생성할 때 기본 타임아웃을 1시간으로 설정하고 있기 때문에
이에 맞춰서 클라이언트의 타임아웃도 1시간으로 변경합니다.
=> [FE] #234: 사용자 구독 요청 기본 timeOut 설정 변경

server/src/main/java/com/hexacore/tayo/car/CarService.java, server/src/main/java/com/hexacore/tayo/category/CategoryCustomRepository.java, server/src/main/java/com/hexacore/tayo/category/CategoryCustomRepositoryImpl.java, server/src/main/java/com/hexacore/tayo/category/CategoryRepository.java, server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java, server/src/main/java/com/hexacore/tayo/util/S3Manager.java, server/src/test/java/com/hexacore/tayo/TestConfig.java, server/src/test/java/com/hexacore/tayo/car/CarRepositoryTest.java, server/src/test/java/com/hexacore/tayo/car/CarServiceCreateCarTest.java, server/src/test/java/com/hexacore/tayo/car/CarServiceDeleteCarTest.java, server/src/test/java/com/hexacore/tayo/category/CategoryRepositoryTest.java, server/src/test/java/com/hexacore/tayo/category/CategoryServiceTest.java
=> [BE] #224: 차량 등록, 삭제, 카테고리 조회, 결제 관련 API 리팩토링 및 테스트 코드 수정

server/src/main/java/com/hexacore/tayo/util/S3Manager.java
- before: 이미지 파일명 뒤에 타임스탬프를 추가해서 확장자가 달라지는 경우 발생
- after: 타임스탬프를 이미지 파일명 앞에 추가하는 걸로 수정
=> [BE] HOTFIX: S3 Manager 파일 명에서 유효하지 않은 확장자명이 들어가는 버그 수정

client/src/pages/hosts/HostRegister.tsx, client/src/pages/hosts/hostsRoutes.tsx
close #256 
- 차량 등록/수정 페이지에서 서버 연결이 안될 경우 렌더링되도록 수정 
- "서버에 연결할 수 없습니다. 다시 시도해 주세요." 메시지만 나오는 화면을 보이도록 변경
- useEffect Hook에서 서버에 연결을 실패하거나 API 요청 상태가 'rejected'일 경우의 예외 처리
=> [FE] #256: 차량 등록/수정 페이지에서 서버 연결이 안될 경우에도 렌더링되도록 수정

server/src/main/java/com/hexacore/tayo/car/CarController.java, server/src/main/java/com/hexacore/tayo/car/CarService.java, server/src/main/java/com/hexacore/tayo/car/dto/CreateCarRequestDto.java, server/src/main/java/com/hexacore/tayo/car/dto/GetPresignedUrlsRequestDto.java, server/src/main/java/com/hexacore/tayo/car/dto/GetPresignedUrlsResposneDto.java, server/src/main/java/com/hexacore/tayo/car/dto/UpdateCarRequestDto.java, server/src/main/java/com/hexacore/tayo/util/S3Manager.java, server/src/test/java/com/hexacore/tayo/car/CarServiceCreateCarTest.java, server/src/test/java/com/hexacore/tayo/car/CarServiceDeleteCarTest.java
close(#259)
Request Parameter
* `fileName`: string (ex. "image.png")
* `fileType`: string (ex. "image/png")
* `prefix?`: string (ex. "downscaled_")
```
/cars/presigned-urls?fileName={fileName}&fileType={fileType}&prefix={prefix}
```
Response
* prefix가 전달된 경우 downscaledPresignedUrl도 함께 제공, prefix가 전달되지 않은 경우에는 downscaledPresignedUrl = null
```json
{
"success": true,
"code": 200,
"message": "OK",
"data": {
"originalPresignedUrl": "https://hexacore-bucket.s3.ap-northeast-2.amazonaws.com/hello?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240224T161849Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Expires=299&X-Amz-Credential=AKIARJRPQGMHXHKHPN4W%2F20240224%2Fap-northeast-2%2Fs3%2Faws4_request&X-Amz-Signature=1e0b8e96c8e7f56e57dfcd33f325a0edcbc9194df452a212943828117d3c8cca", …
```
=> [BE] #259: Pre-signed URL 적용

.github/workflows/be-gradle.yml
* 백엔드 배포 브랜치 이름을 deploy-BE로 변경했습니다.
=> [BE] hotfix: 백엔드 배포 브랜치 deploy-BE로 변경

client/src/pages/home/components/sidebar/SideBar.tsx
close(#277)
기존에는 "필터 적용하기" 버튼을 클릭하면 `queryString.append()` 방식으로 조건을 추가하여, 중복된 필터링 조건을 다시 적용하는 경우 중복된 key-value가 추가되어 조건이 적용되지 않는 이슈가 있었습니다. 따라서 `queryString.set()` 메서드를 사용하여 중복된 key를 추가하려는 경우에는 업데이트가 되도록 수정했습니다.
=> [FE] #277: 검색 화면에서 필터링 적용이 되지 않는 이슈
